import React from 'react';
import { Bot, X, FileText, Activity } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface AIAnalysisModalProps {
    isOpen: boolean;
    onClose: () => void;
    content: string;
    isLoading: boolean;
}

export const AIAnalysisModal: React.FC<AIAnalysisModalProps> = ({ isOpen, onClose, content, isLoading }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fade-in">
            <div className="bg-slate-900 border border-slate-700 rounded-xl shadow-2xl w-full max-w-2xl max-h-[80vh] flex flex-col">
                <div className="flex items-center justify-between p-6 border-b border-slate-800">
                    <div className="flex items-center gap-3">
                        <div className="bg-purple-600/20 p-2 rounded-lg">
                            <Bot className="w-6 h-6 text-purple-400" />
                        </div>
                        <div>
                            <h3 className="text-lg font-bold text-slate-100">Gemini Diagnostics</h3>
                            <p className="text-xs text-slate-400">Automated log analysis & troubleshooting</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="text-slate-500 hover:text-white transition-colors">
                        <X className="w-6 h-6" />
                    </button>
                </div>

                <div className="p-6 overflow-y-auto flex-1 text-slate-300">
                    {isLoading ? (
                        <div className="flex flex-col items-center justify-center py-12 space-y-4">
                            <div className="w-8 h-8 border-2 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
                            <p className="text-sm text-purple-300 animate-pulse">Analyzing log patterns with Gemini AI...</p>
                        </div>
                    ) : (
                        <div className="prose prose-invert prose-sm max-w-none">
                            <ReactMarkdown
                                components={{
                                    h1: ({ node, ...props }) => <h1 className="text-xl font-bold text-purple-300 mb-4" {...props} />,
                                    h2: ({ node, ...props }) => <h2 className="text-lg font-semibold text-slate-200 mt-6 mb-3 border-b border-slate-800 pb-2" {...props} />,
                                    ul: ({ node, ...props }) => <ul className="list-disc pl-5 space-y-2 text-slate-300" {...props} />,
                                    li: ({ node, ...props }) => <li className="marker:text-purple-500" {...props} />,
                                    strong: ({ node, ...props }) => <strong className="text-white font-semibold" {...props} />
                                }}
                            >
                                {content}
                            </ReactMarkdown>
                        </div>
                    )}
                </div>

                <div className="p-4 bg-[#000410] border-t border-slate-800 rounded-b-xl flex justify-between items-center text-xs text-slate-500">
                    <span className="flex items-center gap-1">
                        <Activity className="w-3 h-3" />
                        Analysis generated by Google Gemini 2.5 Flash
                    </span>
                    <button
                        onClick={onClose}
                        className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors font-medium"
                    >
                        Close Report
                    </button>
                </div>
            </div>
        </div>
    );
};