$certDir = "server/certs"
$pfxPath = "$certDir/cert.pfx"

function Get-RandomPassword {
    param (
        [int]$Length = 24
    )
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    $random = New-Object System.Random
    $password = ""
    for ($i = 0; $i -lt $Length; $i++) {
        $password += $chars[$random.Next(0, $chars.Length)]
    }
    return $password
}

if (-not (Test-Path $certDir)) {
    Write-Host "[certs] Creating directory: $certDir" -ForegroundColor Cyan
    New-Item -ItemType Directory -Force -Path $certDir
}

# Determine Password
$passwordFile = "$certDir/PASSWORD.md"
if (Test-Path $passwordFile) {
    $content = Get-Content $passwordFile -Raw
    # Format: ```txt\nPassword: <pass>\n...```
    if ($content -match 'Password:\s+([a-zA-Z0-9]+)') {
        $password = $matches[1].Trim()
    }
    else {
        $password = "password" # Fallback
    }
}
else {
    $password = Get-RandomPassword
    $mdContent = @"
# Certificate Password

``````txt
Password: $password
Generated by UptimeSHIELD
``````
"@
    $mdContent | Set-Content -Path $passwordFile -Encoding utf8
}


if (-not (Test-Path $pfxPath)) {
    Write-Host "[certs] cert.pfx missing. Generating..." -ForegroundColor Yellow
    if (Get-Command openssl -ErrorAction SilentlyContinue) {
        Write-Host "[certs] Using OpenSSL..." -ForegroundColor Cyan
        $keyPath = "$certDir/key.pem"
        $certPath = "$certDir/cert.pem"
        # Generate PEMs
        openssl req -x509 -newkey rsa:4096 -keyout $keyPath -out $certPath -nodes -days 365 -subj "/CN=localhost"
        # Convert to PFX
        openssl pkcs12 -export -out $pfxPath -inkey $keyPath -in $certPath -password "pass:$password"
    }
    else {
        Write-Host "[certs] OpenSSL not found. Using PowerShell (Native Windows)..." -ForegroundColor Cyan
        $cert = New-SelfSignedCertificate -DnsName "localhost" -CertStoreLocation "Cert:\CurrentUser\My" -Type Custom -KeySpec Signature -Subject "CN=localhost"
        $secPassword = ConvertTo-SecureString -String $password -Force -AsPlainText
        Export-PfxCertificate -Cert $cert -FilePath $pfxPath -Password $secPassword
    }
}
else {
    Write-Host "[certs] cert.pfx found." -ForegroundColor Green
}
